# Generated by Django 3.1.3 on 2020-11-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201115_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='money',
        ),
    ]
