# Generated by Django 3.1.3 on 2020-11-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='A promising tech company')),
                ('ltp', models.FloatField(default=1000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('units', models.IntegerField()),
                ('price_each', models.FloatField()),
                ('transaction', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], max_length=5)),
                ('Stock', models.ForeignKey(default='Deleted Stock', on_delete=django.db.models.deletion.SET_DEFAULT, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=1000.0)),
                ('time', models.TimeField(auto_now=True)),
                ('mean_price', models.FloatField(default=1000.0)),
                ('variance', models.FloatField(default=200)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
