# Generated by Django 3.1.3 on 2020-11-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20201115_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='full_name',
            field=models.CharField(default='Tech Company', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='SY', max_length=10),
        ),
    ]
