# Generated by Django 3.1.3 on 2020-11-19 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_auto_20201115_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='mean_price',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='variance',
        ),
        migrations.AddField(
            model_name='stockprice',
            name='variance_lower_bound',
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='variance_upper_bound',
            field=models.FloatField(default=1.1),
        ),
        migrations.CreateModel(
            name='UserAccountValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('value', models.FloatField(default=10000.0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountCurrentValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=10000.0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
