# Generated by Django 3.1.3 on 2020-11-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201119_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='variance_lower_bound',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='variance_upper_bound',
        ),
    ]
