# Generated by Django 3.1.3 on 2020-11-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20201119_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccountCurrentValue',
        ),
    ]
