# Generated by Django 3.1.3 on 2020-11-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20201119_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
