# Generated by Django 3.1.3 on 2020-11-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20201119_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvalue',
            name='holdings_value',
            field=models.FloatField(default=0.0),
        ),
    ]
