# Generated by Django 3.1.3 on 2020-11-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_accountvalue_holdings_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
