# Generated by Django 3.1.3 on 2020-11-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_portfolio_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='time',
        ),
    ]
