# Generated by Django 3.1.3 on 2020-11-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_remove_portfolio_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ltp',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='variance_lower_bound',
            field=models.FloatField(default=0.99),
        ),
        migrations.AlterField(
            model_name='stock',
            name='variance_upper_bound',
            field=models.FloatField(default=1.01),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='price',
            field=models.FloatField(default=100.0),
        ),
    ]
