# Generated by Django 3.1.3 on 2020-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20201120_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvalue',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
